[package]
name = "wayland-monitor-detector"
version = "0.1.0"
edition = "2024"

[dependencies]
wayland-client = "0.31.12"
wayland-protocols-wlr = {  version = "0.3.10", features = ["client"] }
wayland-protocols = { version = "0.32.10", features = ["client"] }
